update

diff --git a/patches/0006-add-lede-profile.patch b/patches/0006-add-lede-profile.patch
--- a/patches/0006-add-lede-profile.patch
+++ b/patches/0006-add-lede-profile.patch
@@ -1,37 +1,113 @@
 From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001
 From: teasiu <teasiu@qq.com>
-Date: Sat, 3 Apr 2021 16:42:37 +0800
-Subject: [PATCH 6/6] add lede profile
+Date: Sat, 15 May 2021 08:49:45 +0800
+Subject: [PATCH] add lede profile
 
 Signed-off-by: teasiu <teasiu@qq.com>
 ---
- package/base-files/files/etc/profile | 16 ++++++++++++++++
- 1 file changed, 16 insertions(+)
+ package/base-files/files/etc/profile | 78 +++++++++++++++++++++-------
+ 1 file changed, 60 insertions(+), 18 deletions(-)
 
 diff --git a/package/base-files/files/etc/profile b/package/base-files/files/etc/profile
-index 0beff1608..c29194073 100644
+index 0beff16..984626f 100644
 --- a/package/base-files/files/etc/profile
 +++ b/package/base-files/files/etc/profile
-@@ -38,3 +38,19 @@ in order to prevent unauthorized SSH logins.
- --------------------------------------------------
- EOF
- fi
-+
-+Target=$([ -f /etc/openwrt_info ] && cat /etc/openwrt_info | awk 'NR==3')
-+Version=$([ -f /etc/openwrt_info ] && cat /etc/openwrt_info | awk 'NR==1')
-+[ -z "${Target}" ] && Target=$(jsonfilter -e '@.model.id' < /etc/board.json | tr ',' '_')
-+IP_Address=$(ifconfig -a | grep inet | grep -v 127.0.0.1 | grep -v inet6 | awk '{print $2}' | tr -d "addr:" | awk 'NR==1')
-+CoreMark=$([ -f /etc/bench.log ] && egrep -o "[0-9]+" /etc/bench.log | awk 'NR==1')
-+[ -z "${CoreMark}" ] && CoreMark=0
-+Srartup=$(awk '{a=$1/86400;b=($1%86400)/3600;c=($1%3600)/60} {printf("%d 天 %d 小时 %d 分钟\n",a,b,c)}' /proc/uptime)
-+Overlay_Available="$(df -h | grep ":/overlay" | awk '{print $4}' | awk 'NR==1')"
-+
-+echo -e "\n\n           设备名称:		${Target}"
-+echo "           固件版本:		${Version}"
-+echo "           IP 地址: 		${IP_Address}"
-+echo "           运行时间: 		${Srartup}"
-+echo "           CoreMark 得分: 	${CoreMark}"
-+echo -e "           可用空间:		${Overlay_Available}\n"
+@@ -1,14 +1,50 @@
+-[ -e /tmp/.failsafe ] && export FAILSAFE=1
++Sysinfo() {
++	[ -f /etc/openwrt_info ] && source /etc/openwrt_info > /dev/null 2>&1
++	export Target=${DEFAULT_Device}
++	[ -n "${CURRENT_Version}" ] && export Version="${CURRENT_Version}" || Version=Unknown
++	[ -z "${Target}" ] && export Target=$(jsonfilter -e '@.model.id' < /etc/board.json | tr ',' '_')
++	export IP_Address=$(ifconfig -a | grep inet | grep -v 127.0.0.1 | grep -v inet6 | awk '{print $2}' | tr -d "addr:" | awk 'NR==1')
++	export CoreMark=$([ -f /etc/bench.log ] && egrep -o "[0-9]+" /etc/bench.log | awk 'NR==1')
++	export Startup=$(awk '{a=$1/86400;b=($1%86400)/3600;c=($1%3600)/60} {printf("%d 天 %d 小时 %d 分钟\n",a,b,c)}' /proc/uptime)
++	export Overlay_Available="$(df -h | grep ":/overlay" | awk '{print $4}' | awk 'NR==1')"
++	export TEMP=$(sensors 2>/dev/null | grep 'Core 0' | awk '{print $3}')
++	echo -e "\n           设备名称:		${Yellow}$(uname -n) / ${Target}${White}"
++	[ -n "${TEMP}" ] && echo "           核心温度:		${TEMP}"
++	echo "           内核版本:		$(uname -rs)"
++	echo -e "           固件版本:		${Skyb}${Version}${White}"
++	echo "           IP 地址 : 		${IP_Address}"
++	echo "           可用空间:		${Overlay_Available}"
++	echo "           运行时间: 		${Startup}"
++	[ -n "${CoreMark}" ] && echo "           性能得分:		${CoreMark}"
++	echo ""
++}
+ 
+-[ -f /etc/banner ] && cat /etc/banner
+-[ -n "$FAILSAFE" ] && cat /etc/banner.failsafe
++White="\e[0m"
++Yellow="\e[33m"
++Red="\e[31m"
++Blue="\e[34m"
++Skyb="\e[36m"
+ 
++clear
++[ -e /tmp/.failsafe ] && export FAILSAFE=1
++[ -f /etc/banner ] && {
++	echo -e "$Blue"
++	cat /etc/banner
++	echo -e "$White"
++}
++[ -n "$FAILSAFE" ] && {
++	echo -e "$Red"
++	cat /etc/banner.failsafe
++	echo -e "$White"
++}
+ fgrep -sq '/ overlay ro,' /proc/mounts && {
+-	echo 'Your JFFS2-partition seems full and overlayfs is mounted read-only.'
+-	echo 'Please try to remove files from /overlay/upper/... and reboot!'
++	echo -e "$Red"
++	echo "警告: 您的固件空间已满,接下来保存的数据将会面临丢失的风险."
++	echo "请尝试从 /overlay 删除一些文件并重启设备!"
++	echo -e "$White"
+ }
+ 
+-export PATH="%PATH%"
++export PATH="/usr/sbin:/usr/bin:/sbin:/bin"
+ export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
+ export HOME=${HOME:-/root}
+ export PS1='\u@\h:\w\$ '
+@@ -21,20 +57,26 @@ case "$TERM" in
+ esac
+ 
+ [ -n "$FAILSAFE" ] || {
+-	for FILE in /etc/profile.d/*.sh; do
++	for FILE in /etc/profile.d/*.sh
++	do
+ 		[ -e "$FILE" ] && . "$FILE"
+ 	done
+ 	unset FILE
+ }
+ 
+-if ( grep -qs '^root::' /etc/shadow && \
+-     [ -z "$FAILSAFE" ] )
+-then
+-cat << EOF
+-=== WARNING! =====================================
+-There is no root password defined on this device!
+-Use the "passwd" command to set up a new password
+-in order to prevent unauthorized SSH logins.
+---------------------------------------------------
+-EOF
+-fi
++Sysinfo
++alias autoupdate='bash /bin/AutoUpdate.sh'
++alias AutoUpdate='bash /bin/AutoUpdate.sh'
++alias Tools='bash /bin/AutoBuild*.sh'
++alias tools='bash /bin/AutoBuild*.sh'
++alias coremarkd='bash /etc/coremark.sh'
++alias shutdown='sync && poweroff'
++alias ll='ls -alF --color=auto'
++service() {
++	[ -f "/etc/init.d/$1" ] || {
++		echo "service "'"'"$1"'"'" not found, the following services are available:"
++		ls "/etc/init.d"
++		return 1
++	}
++	/etc/init.d/$@
++}
 -- 
 2.20.1
 
